name: main

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build_package_publish:
    name: "init → build → test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: init
        run: |
          make init
          
      - name: build
        run: |
          make build version=$GITHUB_RUN_ID

      - name: test
        run: |
          make server
          make test version=$GITHUB_RUN_ID

      - name: publish
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "reports/xunit/*.xml"
