name: main

on: 
  push:
    tags: [ v1.* ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

jobs:
  build_package_publish:
    name: "init → build →  package → release → deploy → invalidate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: init
        run: |
          make init
          
      - name: build
        run: |
          make build
          
      - name: package
        run: |
          make package
          
      - name: release
        run: |
          make version=$GITHUB_REF_NAME release
      
      - name: deploy
        run: |
          make deploy
      
      - name: invalidate
        run: |
          make invalidate
